<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require_once "vendor/autoload.php";

//PHPMailer Object
$mail = new PHPMailer(true);

//Argument true in constructor enables exceptions
$mail->SMTPDebug = 2;$mail->isSMTP();
$mail->Host = 'smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Username = 'gngsoftech@gmail.com'; 

//paste one generated by Mailtrap
$mail->Password = 'bcdblaxuzovnqizo'; 

//paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->AuthType = 'PLAIN';
$mail->Port = 587;

//From email address and name
$mail->From = "azaharmyra95@gmail.com";
$mail->FromName = "G&G Softech Sdn Bhd";

//To address and name
$mail->addAddress("mirapsm95@gmail.com", "Mira");

//Address to which recipient will reply
$mail->addReplyTo("care@gongetz.com", "Reply");

//CC and BCC
$mail->addCC("cc@example.com");
$mail->addBCC("bcc@example.com");

//Send HTML or Plain Text email
$mail->isHTML(true);

$mail->Subject = "Subject Text";
$mail->Body = "<i>Mail body in HTML</i>";
$mail->AltBody = "This is the plain text version of the email content";

try { $mail->send(); echo "Message has been sent successfully";} 

catch (Exception $e) { echo "Mailer Error: " . $mail->ErrorInfo;}?>
