<?php
require 'vendor/autoload.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use Kreait\Firebase;
use Kreait\Firebase\Messaging\CloudMessage;

if (isset($_POST['add_news'])) 
{
  $access = $_POST['access'];
  $title = $_POST['title'];
  $detail = $_POST['detail'];
  $staff_id = strval($_SESSION["loggeduser_id"]);
  $school_id = $_SESSION["loggeduser_schoolID"];
  $date = new MongoDB\BSON\UTCDateTime((new DateTime('now'))->getTimestamp()*1000);

  $bulk = new MongoDB\Driver\BulkWrite(['ordered'=>true]);
  $bulk->insert([
    'School_id'=>$school_id,
    'Staff_id'=>$staff_id,
    'Title'=>$title,
    'Details'=>$detail,
    'Access'=>$access,
    'Status'=>'ACTIVE',
    'Date'=>$date]);
  $writeConcern = new MongoDB\Driver\WriteConcern(MongoDB\Driver\WriteConcern::MAJORITY, 1000);
  try
  {
    $result =$GoNGetzDatabase->executeBulkWrite('GoNGetzSmartSchool.News', $bulk, $writeConcern);
  }
  catch (MongoDB\Driver\Exception\BulkWriteException $e)
  {
    $result = $e->getWriteResult();
    // Check if the write concern could not be fulfilled
    if ($writeConcernError = $result->getWriteConcernError())
    {
        printf("%s (%d): %s\n",
            $writeConcernError->getMessage(),
            $writeConcernError->getCode(),
            var_export($writeConcernError->getInfo(), true)
        );
    }
    // Check if any write operations did not complete at all
    foreach ($result->getWriteErrors() as $writeError) {
        printf("Operation#%d: %s (%d)\n",
            $writeError->getIndex(),
            $writeError->getMessage(),
            $writeError->getCode()
        );
    }
  }
  catch (MongoDB\Driver\Exception\Exception $e)
  {
    printf("Other error: %s\n", $e->getMessage());
    exit;
  }
  printf("Inserted %d document(s)\n", $result->getInsertedCount());

  $date = new MongoDB\BSON\UTCDateTime((new DateTime('now'))->getTimestamp()*1000);
  $utcdatetime = new MongoDB\BSON\UTCDateTime(strval($date));
  $datetime = $utcdatetime->toDateTime()->setTimezone(new \DateTimeZone(date_default_timezone_get()));
  $date = date_format($datetime,"d M Y");

  $Bcc = $_POST['access'];
  $FromNameF = $_SESSION["loggeduser_consumerFName"];
  $FromNameL = $_SESSION["loggeduser_consumerLName"];
  $SchoolName = $_SESSION["loggeduser_schoolName"];
  $SchoolEmail = $_SESSION["loggeduser_SchoolsEmail"];

  $Emails = array();

  if ($Bcc == 'STAFF')
  {
    $filter = ['SchoolID'=>$_SESSION["loggeduser_schoolID"]];
    $query = new MongoDB\Driver\Query($filter);
    $cursor = $GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.Staff',$query);
    foreach ($cursor as $document)
    {
      $ConsumerID = $document->ConsumerID;
      $StaffLevel = strval($document->StaffLevel);
      
      if ($StaffLevel == 1)
      {
        $filter = ['_id'=>new \MongoDB\BSON\ObjectID($ConsumerID)];
        $query = new MongoDB\Driver\Query($filter);
        $cursor = $GoNGetzDatabase->executeQuery('GoNGetz.Consumer',$query);
        foreach ($cursor as $document1)
        {
          $ConsumerIDNo = $document1->ConsumerIDNo;
          $ConsumerFName = $document1->ConsumerFName;
          $ConsumerLName = $document1->ConsumerLName;
          $Email = $document1->ConsumerEmail;
          if($Email != "")
          {
            //PHPMailer Object
            $mail = new PHPMailer(true);
            $mail->SMTPOptions = array(
                'ssl' => array(
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                    'allow_self_signed' => true
                )
            );
            //Argument true in constructor enables exceptions
            //$mail->SMTPDebug = 2;
            $mail->isSMTP();
            $mail->Host = 'mail.gongetz.com';
            $mail->SMTPAuth = true;
            $mail->Username = 'noreply@gongetz.com'; 

            //paste one generated by Mailtrap
            $mail->Password = 'zaq12wsx'; 

            //paste one generated by Mailtrap
            $mail->SMTPSecure = 'tls';
            $mail->AuthType = 'PLAIN';
            $mail->Port = 25;

            //From email address and name
            $mail->From =  'noreply@gongetz.com'; 
            $mail->FromName = $SchoolName;

            //To address and name
            $mail->addAddress($Email,$ConsumerFName);

            //Address to which recipient will reply
            $mail->addReplyTo($Email,$ConsumerFName);

            //CC and BCC
            $mail->addCC("gngsoftech@gmail.com");
            
            //Send HTML or Plain Text email
            $mail->isHTML(true);

            $mail->Subject = "$SchoolName  - $title";
            $mail->Body ="
            <html>
              <head>
                <meta name='viewport' content='width=device-width'>
                <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
                <title>Simple Transactional Email</title>
                <style>
                /* -------------------------------------
                    INLINED WITH htmlemail.io/inline
                ------------------------------------- */
                /* -------------------------------------
                    RESPONSIVE AND MOBILE FRIENDLY STYLES
                ------------------------------------- */
                @media only screen and (max-width: 620px) {
                  table[class=body] h1 {
                    font-size: 28px !important;
                    margin-bottom: 10px !important;
                  }
                  table[class=body] p,
                        table[class=body] ul,
                        table[class=body] ol,
                        table[class=body] td,
                        table[class=body] span,
                        table[class=body] a {
                    font-size: 16px !important;
                  }
                  table[class=body] .wrapper,
                        table[class=body] .article {
                    padding: 10px !important;
                  }
                  table[class=body] .content {
                    padding: 0 !important;
                  }
                  table[class=body] .container {
                    padding: 0 !important;
                    width: 100% !important;
                  }
                  table[class=body] .main {
                    border-left-width: 0 !important;
                    border-radius: 0 !important;
                    border-right-width: 0 !important;
                  }
                  table[class=body] .btn table {
                    width: 100% !important;
                  }
                  table[class=body] .btn a {
                    width: 100% !important;
                  }
                  table[class=body] .img-responsive {
                    height: auto !important;
                    max-width: 100% !important;
                    width: auto !important;
                  }
                }

                /* -------------------------------------
                    PRESERVE THESE STYLES IN THE HEAD
                ------------------------------------- */
                @media all {
                  .ExternalClass {
                    width: 100%;
                  }
                  .ExternalClass,
                        .ExternalClass p,
                        .ExternalClass span,
                        .ExternalClass font,
                        .ExternalClass td,
                        .ExternalClass div {
                    line-height: 100%;
                  }
                  .apple-link a {
                    color: inherit !important;
                    font-family: inherit !important;
                    font-size: inherit !important;
                    font-weight: inherit !important;
                    line-height: inherit !important;
                    text-decoration: none !important;
                  }
                  #MessageViewBody a {
                    color: inherit;
                    text-decoration: none;
                    font-size: inherit;
                    font-family: inherit;
                    font-weight: inherit;
                    line-height: inherit;
                  }
                  .btn-primary table td:hover {
                    background-color: #34495e !important;
                  }
                  .btn-primary a:hover {
                    background-color: #34495e !important;
                    border-color: #34495e !important;
                  }
                }
                </style>
              </head>
              <body class='' style='background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;'>
                <span class='preheader' style='color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;'> You got this email because you're a member of.. </span>
                <table border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;'>
                  <tr>
                    <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                    <td class='container' style='font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;'>
                      <div class='content' style='box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;'>

                        <!-- START CENTERED WHITE CONTAINER -->
                        <table class='main' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;'>

                          <!-- START MAIN CONTENT AREA -->
                          <tr>
                            <td class='wrapper' style='font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;'>
                              <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                                <tr>
                                  <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>
                                    <p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;'> 
                                      <p?>Hi </p><a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'>$ConsumerFName $ConsumerLName</a>,
                                      <p>You've received this email because you're a member of <a href='https://smartschool.gongetz.com/school.php?id=$school_id'>$SchoolName</a></p>
                                      <p>Here's the latest News <a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'> $title </a> from $FromNameF $FromNameL on $date and we thought it might need your attention.</p>
                                      <p>Thanks,<br/>
                                      <p>Go N Getz</p>
                                      <p><small>Please don't reply to this email, it won't go anyway except to our great black hole.</small></p>
                                    </p>
                                    <table border='0' cellpadding='0' cellspacing='0' class='btn btn-primary' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;'>
                                      <tbody>
                                        <tr>
                                          <td align='left' style='font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;'>
                                            <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;'>
                                              <tbody>
                                                <tr>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </table>
                            </td>
                          </tr>

                        <!-- END MAIN CONTENT AREA -->
                        </table>

                        <!-- START FOOTER -->
                        <div class='footer' style='clear: both; Margin-top: 10px; text-align: center; width: 100%;'>
                          <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                            <tr>
                              <td class='content-block' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                                <span class='apple-link' style='color: #999999; font-size: 12px; text-align: center;'>G&G Softech Sdn Bhd, 75-1, jalan pudu lama, 50200, wilayah persekutuan, kuala lumpur</span>
                                <br> Don't like these emails? <a href='mailto:care@gongetz.com' class='btn btn-danger btn-sm'>Report Spam</a>.
                              </td>
                            </tr>
                            <tr>
                              <td class='content-block powered-by' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                              <a href='' style='color: #999999; font-size: 12px; text-align: center; text-decoration: none;'>gongetz.com</a>.
                              </td>
                            </tr>
                          </table>
                        </div>
                        <!-- END FOOTER -->

                      <!-- END CENTERED WHITE CONTAINER -->
                      </div>
                    </td>
                    <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                  </tr>
                </table>
              </body>
            </html>";
            // $mail->AltBody = "This is the plain text version of the email content";

            // try { $mail->send();} 

            // catch (Exception $e) { echo "Mailer Error: " . $mail->ErrorInfo;}

            // //firebase notification//
          
            // $factory = (new Factory)
            //     ->withServiceAccount('/path/to/firebase_credentials.json')
            //     ->withDatabaseUri('https://my-project-default-rtdb.firebaseio.com');

            // $auth = $factory->createAuth();
            // $realtimeDatabase = $factory->createDatabase();
            // $cloudMessaging = $factory->createMessaging();
            // $remoteConfig = $factory->createRemoteConfig();
            // $cloudStorage = $factory->createStorage();
            // $firestore = $factory->createFirestore();
            $mail->AltBody = "This is the plain text version of the email content";
            try { $mail->send();} 
            catch (Exception $e) { echo "Mailer Error: " . $mail->ErrorInfo;}
          }
        }
      }
    }
  }
  elseif ($Bcc == 'TEACHER')
  {
    $filter = ['SchoolID'=>$_SESSION["loggeduser_schoolID"]];
    $query = new MongoDB\Driver\Query($filter);
    $cursor = $GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.Staff',$query);
    foreach ($cursor as $document)
    {
      $ConsumerID = $document->ConsumerID;
      $StaffLevel = strval($document->StaffLevel);

      if ($StaffLevel == 0)
      {
        $filter = ['_id'=>new \MongoDB\BSON\ObjectID($ConsumerID)];
        $query = new MongoDB\Driver\Query($filter);
        $cursor = $GoNGetzDatabase->executeQuery('GoNGetz.Consumer',$query);
        foreach ($cursor as $document1)
        {
          $ConsumerIDNo = $document1->ConsumerIDNo;
          $ConsumerFName = $document1->ConsumerFName;
          $ConsumerLName = $document1->ConsumerLName;
          $Email = $document1->ConsumerEmail;

          if($Email != "")
          {
            //PHPMailer Object
            $mail = new PHPMailer(true);
            $mail->SMTPOptions = array(
                'ssl' => array(
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                    'allow_self_signed' => true
                )
            );
            //Argument true in constructor enables exceptions
            //$mail->SMTPDebug = 2;
            $mail->isSMTP();
            $mail->Host = 'mail.gongetz.com';
            $mail->SMTPAuth = true;
            $mail->Username = 'noreply@gongetz.com'; 

            //paste one generated by Mailtrap
            $mail->Password = 'zaq12wsx'; 

            //paste one generated by Mailtrap
            $mail->SMTPSecure = 'tls';
            $mail->AuthType = 'PLAIN';
            $mail->Port = 25;

            //From email address and name
            $mail->From =  'noreply@gongetz.com'; 
            $mail->FromName = $SchoolName;

            //To address and name
            $mail->addAddress($Email,$ConsumerFName);

            //Address to which recipient will reply
            $mail->addReplyTo($Email,$ConsumerFName);

            //CC and BCC
            $mail->addCC("gngsoftech@gmail.com");
            
            //Send HTML or Plain Text email
            $mail->isHTML(true);

            $mail->Subject = "$SchoolName  - $title";
            $mail->Body ="
            <html>
              <head>
                <meta name='viewport' content='width=device-width'>
                <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
                <title>Simple Transactional Email</title>
                <style>
                /* -------------------------------------
                    INLINED WITH htmlemail.io/inline
                ------------------------------------- */
                /* -------------------------------------
                    RESPONSIVE AND MOBILE FRIENDLY STYLES
                ------------------------------------- */
                @media only screen and (max-width: 620px) {
                  table[class=body] h1 {
                    font-size: 28px !important;
                    margin-bottom: 10px !important;
                  }
                  table[class=body] p,
                        table[class=body] ul,
                        table[class=body] ol,
                        table[class=body] td,
                        table[class=body] span,
                        table[class=body] a {
                    font-size: 16px !important;
                  }
                  table[class=body] .wrapper,
                        table[class=body] .article {
                    padding: 10px !important;
                  }
                  table[class=body] .content {
                    padding: 0 !important;
                  }
                  table[class=body] .container {
                    padding: 0 !important;
                    width: 100% !important;
                  }
                  table[class=body] .main {
                    border-left-width: 0 !important;
                    border-radius: 0 !important;
                    border-right-width: 0 !important;
                  }
                  table[class=body] .btn table {
                    width: 100% !important;
                  }
                  table[class=body] .btn a {
                    width: 100% !important;
                  }
                  table[class=body] .img-responsive {
                    height: auto !important;
                    max-width: 100% !important;
                    width: auto !important;
                  }
                }

                /* -------------------------------------
                    PRESERVE THESE STYLES IN THE HEAD
                ------------------------------------- */
                @media all {
                  .ExternalClass {
                    width: 100%;
                  }
                  .ExternalClass,
                        .ExternalClass p,
                        .ExternalClass span,
                        .ExternalClass font,
                        .ExternalClass td,
                        .ExternalClass div {
                    line-height: 100%;
                  }
                  .apple-link a {
                    color: inherit !important;
                    font-family: inherit !important;
                    font-size: inherit !important;
                    font-weight: inherit !important;
                    line-height: inherit !important;
                    text-decoration: none !important;
                  }
                  #MessageViewBody a {
                    color: inherit;
                    text-decoration: none;
                    font-size: inherit;
                    font-family: inherit;
                    font-weight: inherit;
                    line-height: inherit;
                  }
                  .btn-primary table td:hover {
                    background-color: #34495e !important;
                  }
                  .btn-primary a:hover {
                    background-color: #34495e !important;
                    border-color: #34495e !important;
                  }
                }
                </style>
              </head>
              <body class='' style='background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;'>
                <span class='preheader' style='color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;'> You got this email because you're a member of.. </span>
                <table border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;'>
                  <tr>
                    <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                    <td class='container' style='font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;'>
                      <div class='content' style='box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;'>

                        <!-- START CENTERED WHITE CONTAINER -->
                        <table class='main' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;'>

                          <!-- START MAIN CONTENT AREA -->
                          <tr>
                            <td class='wrapper' style='font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;'>
                              <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                                <tr>
                                  <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>
                                    <p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;'> 
                                      <p?>Hi </p><a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'>$ConsumerFName $ConsumerLName</a>,
                                      <p>You've received this email because you're a member of <a href='https://smartschool.gongetz.com/school.php?id=$school_id'>$SchoolName</a></p>
                                      <p>Here's the latest News <a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'> $title </a> from $FromNameF $FromNameL on $date and we thought it might need your attention.</p>
                                      <p>Thanks,<br/>
                                      <p>Go N Getz</p>
                                      <p><small>Please don't reply to this email, it won't go anyway except to our great black hole.</small></p>
                                    </p>
                                    <table border='0' cellpadding='0' cellspacing='0' class='btn btn-primary' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;'>
                                      <tbody>
                                        <tr>
                                          <td align='left' style='font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;'>
                                            <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;'>
                                              <tbody>
                                                <tr>
                                                </tr>
                                              </tbody>
                                            </table>
                                          </td>
                                        </tr>
                                      </tbody>
                                    </table>
                                  </td>
                                </tr>
                              </table>
                            </td>
                          </tr>

                        <!-- END MAIN CONTENT AREA -->
                        </table>

                        <!-- START FOOTER -->
                        <div class='footer' style='clear: both; Margin-top: 10px; text-align: center; width: 100%;'>
                          <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                            <tr>
                              <td class='content-block' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                                <span class='apple-link' style='color: #999999; font-size: 12px; text-align: center;'>G&G Softech Sdn Bhd, 75-1, jalan pudu lama, 50200, wilayah persekutuan, kuala lumpur</span>
                                <br> Don't like these emails? <a href='mailto:care@gongetz.com' class='btn btn-danger btn-sm'>Report Spam</a>.
                              </td>
                            </tr>
                            <tr>
                              <td class='content-block powered-by' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                              <a href='' style='color: #999999; font-size: 12px; text-align: center; text-decoration: none;'>gongetz.com</a>.
                              </td>
                            </tr>
                          </table>
                        </div>
                        <!-- END FOOTER -->

                      <!-- END CENTERED WHITE CONTAINER -->
                      </div>
                    </td>
                    <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                  </tr>
                </table>
              </body>
            </html>";
          $mail->AltBody = "This is the plain text version of the email content";
          try { $mail->send();} 
          catch (Exception $e) { echo "Mailer Error: " . $mail->ErrorInfo;}
          }
        }
      }
    }
  }
  elseif ($Bcc == 'VIP')
  {
    $filter = ['Schools_id'=>$_SESSION["loggeduser_schoolID"]];
    $query = new MongoDB\Driver\Query($filter);
    $cursor = $GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.Parents',$query);
    foreach ($cursor as $document)
    {
      $ConsumerID = $document->ConsumerID;

      $filter = ['_id'=>new \MongoDB\BSON\ObjectID($ConsumerID)];
      $query = new MongoDB\Driver\Query($filter);
      $cursor = $GoNGetzDatabase->executeQuery('GoNGetz.Consumer',$query);
      foreach ($cursor as $document1)
      {   
        $ConsumerIDNo = $document1->ConsumerIDNo;
        $ConsumerFName = $document1->ConsumerFName;
        $ConsumerLName = $document1->ConsumerLName;
        $Email = $document1->ConsumerEmail;

        if($Email != "")
        {
          //PHPMailer Object
          $mail = new PHPMailer(true);
          $mail->SMTPOptions = array(
              'ssl' => array(
                  'verify_peer' => false,
                  'verify_peer_name' => false,
                  'allow_self_signed' => true
              )
          );
          //Argument true in constructor enables exceptions
          //$mail->SMTPDebug = 2;
          $mail->isSMTP();
          $mail->Host = 'mail.gongetz.com';
          $mail->SMTPAuth = true;
          $mail->Username = 'noreply@gongetz.com'; 

          //paste one generated by Mailtrap
          $mail->Password = 'zaq12wsx'; 

          //paste one generated by Mailtrap
          $mail->SMTPSecure = 'tls';
          $mail->AuthType = 'PLAIN';
          $mail->Port = 25;

          //From email address and name
          $mail->From =  'noreply@gongetz.com'; 
          $mail->FromName = $SchoolName;

          //To address and name
          $mail->addAddress($Email,$ConsumerFName);

          //Address to which recipient will reply
          $mail->addReplyTo($Email,$ConsumerFName);

          //CC and BCC
          $mail->addCC("gngsoftech@gmail.com");
          
          //Send HTML or Plain Text email
          $mail->isHTML(true);

          $mail->Subject = "$SchoolName  - $title";
          $mail->Body ="
          <html>
            <head>
              <meta name='viewport' content='width=device-width'>
              <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
              <title>Simple Transactional Email</title>
              <style>
              /* -------------------------------------
                  INLINED WITH htmlemail.io/inline
              ------------------------------------- */
              /* -------------------------------------
                  RESPONSIVE AND MOBILE FRIENDLY STYLES
              ------------------------------------- */
              @media only screen and (max-width: 620px) {
                table[class=body] h1 {
                  font-size: 28px !important;
                  margin-bottom: 10px !important;
                }
                table[class=body] p,
                      table[class=body] ul,
                      table[class=body] ol,
                      table[class=body] td,
                      table[class=body] span,
                      table[class=body] a {
                  font-size: 16px !important;
                }
                table[class=body] .wrapper,
                      table[class=body] .article {
                  padding: 10px !important;
                }
                table[class=body] .content {
                  padding: 0 !important;
                }
                table[class=body] .container {
                  padding: 0 !important;
                  width: 100% !important;
                }
                table[class=body] .main {
                  border-left-width: 0 !important;
                  border-radius: 0 !important;
                  border-right-width: 0 !important;
                }
                table[class=body] .btn table {
                  width: 100% !important;
                }
                table[class=body] .btn a {
                  width: 100% !important;
                }
                table[class=body] .img-responsive {
                  height: auto !important;
                  max-width: 100% !important;
                  width: auto !important;
                }
              }

              /* -------------------------------------
                  PRESERVE THESE STYLES IN THE HEAD
              ------------------------------------- */
              @media all {
                .ExternalClass {
                  width: 100%;
                }
                .ExternalClass,
                      .ExternalClass p,
                      .ExternalClass span,
                      .ExternalClass font,
                      .ExternalClass td,
                      .ExternalClass div {
                  line-height: 100%;
                }
                .apple-link a {
                  color: inherit !important;
                  font-family: inherit !important;
                  font-size: inherit !important;
                  font-weight: inherit !important;
                  line-height: inherit !important;
                  text-decoration: none !important;
                }
                #MessageViewBody a {
                  color: inherit;
                  text-decoration: none;
                  font-size: inherit;
                  font-family: inherit;
                  font-weight: inherit;
                  line-height: inherit;
                }
                .btn-primary table td:hover {
                  background-color: #34495e !important;
                }
                .btn-primary a:hover {
                  background-color: #34495e !important;
                  border-color: #34495e !important;
                }
              }
              </style>
            </head>
            <body class='' style='background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;'>
              <span class='preheader' style='color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;'> You got this email because you're a member of.. </span>
              <table border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;'>
                <tr>
                  <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                  <td class='container' style='font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;'>
                    <div class='content' style='box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;'>

                      <!-- START CENTERED WHITE CONTAINER -->
                      <table class='main' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;'>

                        <!-- START MAIN CONTENT AREA -->
                        <tr>
                          <td class='wrapper' style='font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;'>
                            <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                              <tr>
                                <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>
                                  <p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;'> 
                                    <p?>Hi </p><a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'>$ConsumerFName $ConsumerLName</a>,
                                    <p>You've received this email because you're a member of <a href='https://smartschool.gongetz.com/school.php?id=$school_id'>$SchoolName</a></p>
                                    <p>Here's the latest News <a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'> $title </a> from $FromNameF $FromNameL on $date and we thought it might need your attention.</p>
                                    <p>Thanks,<br/>
                                    <p>Go N Getz</p>
                                    <p><small>Please don't reply to this email, it won't go anyway except to our great black hole.</small></p>
                                  </p>
                                  <table border='0' cellpadding='0' cellspacing='0' class='btn btn-primary' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;'>
                                    <tbody>
                                      <tr>
                                        <td align='left' style='font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;'>
                                          <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;'>
                                            <tbody>
                                              <tr>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </table>
                          </td>
                        </tr>

                      <!-- END MAIN CONTENT AREA -->
                      </table>

                      <!-- START FOOTER -->
                      <div class='footer' style='clear: both; Margin-top: 10px; text-align: center; width: 100%;'>
                        <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                          <tr>
                            <td class='content-block' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                              <span class='apple-link' style='color: #999999; font-size: 12px; text-align: center;'>G&G Softech Sdn Bhd, 75-1, jalan pudu lama, 50200, wilayah persekutuan, kuala lumpur</span>
                              <br> Don't like these emails? <a href='mailto:care@gongetz.com' class='btn btn-danger btn-sm'>Report Spam</a>.
                            </td>
                          </tr>
                          <tr>
                            <td class='content-block powered-by' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                            <a href='' style='color: #999999; font-size: 12px; text-align: center; text-decoration: none;'>gongetz.com</a>.
                            </td>
                          </tr>
                        </table>
                      </div>
                      <!-- END FOOTER -->

                    <!-- END CENTERED WHITE CONTAINER -->
                    </div>
                  </td>
                  <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                </tr>
              </table>
            </body>
          </html>";
        $mail->AltBody = "This is the plain text version of the email content";
        try { $mail->send();} 
        catch (Exception $e) { echo "Mailer Error: " . $mail->ErrorInfo;}
        }
      }
    }
  }
  else
  {
    $filter = ['SchoolID'=>$_SESSION["loggeduser_schoolID"]];
    $query = new MongoDB\Driver\Query($filter);
    $cursor = $GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.Staff',$query);
    foreach ($cursor as $document)
    {
      $ConsumerID = $document->ConsumerID;

      $filter = ['_id'=>new \MongoDB\BSON\ObjectID($ConsumerID)];
      $query = new MongoDB\Driver\Query($filter);
      $cursor = $GoNGetzDatabase->executeQuery('GoNGetz.Consumer',$query);
      foreach ($cursor as $document1)
      {
        $ConsumerIDNo = $document1->ConsumerIDNo;
        $ConsumerFName = $document1->ConsumerFName;
        $ConsumerLName = $document1->ConsumerLName;
        $Email = $document1->ConsumerEmail;

        if($Email != "")
        {
          //PHPMailer Object
          $mail = new PHPMailer(true);
          $mail->SMTPOptions = array(
              'ssl' => array(
                  'verify_peer' => false,
                  'verify_peer_name' => false,
                  'allow_self_signed' => true
              )
          );
          //Argument true in constructor enables exceptions
          //$mail->SMTPDebug = 2;
          $mail->isSMTP();
          $mail->Host = 'mail.gongetz.com';
          $mail->SMTPAuth = true;
          $mail->Username = 'noreply@gongetz.com'; 

          //paste one generated by Mailtrap
          $mail->Password = 'zaq12wsx'; 

          //paste one generated by Mailtrap
          $mail->SMTPSecure = 'tls';
          $mail->AuthType = 'PLAIN';
          $mail->Port = 25;

          //From email address and name
          $mail->From =  'noreply@gongetz.com'; 
          $mail->FromName = $SchoolName;

          //To address and name
          $mail->addAddress($Email,$ConsumerFName);

          //Address to which recipient will reply
          $mail->addReplyTo($Email,$ConsumerFName);

          //CC and BCC
          $mail->addCC("gngsoftech@gmail.com");
          
          //Send HTML or Plain Text email
          $mail->isHTML(true);

          $mail->Subject = "$SchoolName  - $title";
          $mail->Body ="
          <html>
            <head>
              <meta name='viewport' content='width=device-width'>
              <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
              <title>Simple Transactional Email</title>
              <style>
              /* -------------------------------------
                  INLINED WITH htmlemail.io/inline
              ------------------------------------- */
              /* -------------------------------------
                  RESPONSIVE AND MOBILE FRIENDLY STYLES
              ------------------------------------- */
              @media only screen and (max-width: 620px) {
                table[class=body] h1 {
                  font-size: 28px !important;
                  margin-bottom: 10px !important;
                }
                table[class=body] p,
                      table[class=body] ul,
                      table[class=body] ol,
                      table[class=body] td,
                      table[class=body] span,
                      table[class=body] a {
                  font-size: 16px !important;
                }
                table[class=body] .wrapper,
                      table[class=body] .article {
                  padding: 10px !important;
                }
                table[class=body] .content {
                  padding: 0 !important;
                }
                table[class=body] .container {
                  padding: 0 !important;
                  width: 100% !important;
                }
                table[class=body] .main {
                  border-left-width: 0 !important;
                  border-radius: 0 !important;
                  border-right-width: 0 !important;
                }
                table[class=body] .btn table {
                  width: 100% !important;
                }
                table[class=body] .btn a {
                  width: 100% !important;
                }
                table[class=body] .img-responsive {
                  height: auto !important;
                  max-width: 100% !important;
                  width: auto !important;
                }
              }

              /* -------------------------------------
                  PRESERVE THESE STYLES IN THE HEAD
              ------------------------------------- */
              @media all {
                .ExternalClass {
                  width: 100%;
                }
                .ExternalClass,
                      .ExternalClass p,
                      .ExternalClass span,
                      .ExternalClass font,
                      .ExternalClass td,
                      .ExternalClass div {
                  line-height: 100%;
                }
                .apple-link a {
                  color: inherit !important;
                  font-family: inherit !important;
                  font-size: inherit !important;
                  font-weight: inherit !important;
                  line-height: inherit !important;
                  text-decoration: none !important;
                }
                #MessageViewBody a {
                  color: inherit;
                  text-decoration: none;
                  font-size: inherit;
                  font-family: inherit;
                  font-weight: inherit;
                  line-height: inherit;
                }
                .btn-primary table td:hover {
                  background-color: #34495e !important;
                }
                .btn-primary a:hover {
                  background-color: #34495e !important;
                  border-color: #34495e !important;
                }
              }
              </style>
            </head>
            <body class='' style='background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;'>
              <span class='preheader' style='color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;'> You got this email because you're a member of.. </span>
              <table border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;'>
                <tr>
                  <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                  <td class='container' style='font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;'>
                    <div class='content' style='box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;'>

                      <!-- START CENTERED WHITE CONTAINER -->
                      <table class='main' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;'>

                        <!-- START MAIN CONTENT AREA -->
                        <tr>
                          <td class='wrapper' style='font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;'>
                            <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                              <tr>
                                <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>
                                  <p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;'> 
                                    <p?>Hi </p><a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'>$ConsumerFName $ConsumerLName</a>,
                                    <p>You've received this email because you're a member of <a href='https://smartschool.gongetz.com/school.php?id=$school_id'>$SchoolName</a></p>
                                    <p>Here's the latest News <a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'> $title </a> from $FromNameF $FromNameL on $date and we thought it might need your attention.</p>
                                    <p>Thanks,<br/>
                                    <p>Go N Getz</p>
                                    <p><small>Please don't reply to this email, it won't go anyway except to our great black hole.</small></p>
                                  </p>
                                  <table border='0' cellpadding='0' cellspacing='0' class='btn btn-primary' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;'>
                                    <tbody>
                                      <tr>
                                        <td align='left' style='font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;'>
                                          <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;'>
                                            <tbody>
                                              <tr>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </table>
                          </td>
                        </tr>

                      <!-- END MAIN CONTENT AREA -->
                      </table>

                      <!-- START FOOTER -->
                      <div class='footer' style='clear: both; Margin-top: 10px; text-align: center; width: 100%;'>
                        <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                          <tr>
                            <td class='content-block' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                              <span class='apple-link' style='color: #999999; font-size: 12px; text-align: center;'>G&G Softech Sdn Bhd, 75-1, jalan pudu lama, 50200, wilayah persekutuan, kuala lumpur</span>
                              <br> Don't like these emails? <a href='mailto:care@gongetz.com' class='btn btn-danger btn-sm'>Report Spam</a>.
                            </td>
                          </tr>
                          <tr>
                            <td class='content-block powered-by' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                            <a href='' style='color: #999999; font-size: 12px; text-align: center; text-decoration: none;'>gongetz.com</a>.
                            </td>
                          </tr>
                        </table>
                      </div>
                      <!-- END FOOTER -->

                    <!-- END CENTERED WHITE CONTAINER -->
                    </div>
                  </td>
                  <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                </tr>
              </table>
            </body>
          </html>";
        $mail->AltBody = "This is the plain text version of the email content";
        try { $mail->send();} 
        catch (Exception $e) { echo "Mailer Error: " . $mail->ErrorInfo;}
        }
      }
    }

    $filter = ['Schools_id'=>$_SESSION["loggeduser_schoolID"]];
    $query = new MongoDB\Driver\Query($filter);
    $cursor = $GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.Parent',$query);
    foreach ($cursor as $document)
    {
      $ConsumerID = strval($document->ConsumerID);
      
      $filter = ['_id'=>new \MongoDB\BSON\ObjectID($ConsumerID)];
      $query = new MongoDB\Driver\Query($filter);
      $cursor = $GoNGetzDatabase->executeQuery('GoNGetz.Consumer',$query);
      foreach ($cursor as $document1)
      {
        $ConsumerIDNo = $document1->ConsumerIDNo;
        $ConsumerFName = $document1->ConsumerFName;
        $ConsumerLName = $document1->ConsumerLName;
        $Email = $document1->ConsumerEmail;

        if($Email != "")
        {
          //PHPMailer Object
          $mail = new PHPMailer(true);
          $mail->SMTPOptions = array(
              'ssl' => array(
                  'verify_peer' => false,
                  'verify_peer_name' => false,
                  'allow_self_signed' => true
              )
          );
          //Argument true in constructor enables exceptions
          //$mail->SMTPDebug = 2;
          $mail->isSMTP();
          $mail->Host = 'mail.gongetz.com';
          $mail->SMTPAuth = true;
          $mail->Username = 'noreply@gongetz.com'; 

          //paste one generated by Mailtrap
          $mail->Password = 'zaq12wsx'; 

          //paste one generated by Mailtrap
          $mail->SMTPSecure = 'tls';
          $mail->AuthType = 'PLAIN';
          $mail->Port = 25;

          //From email address and name
          $mail->From =  'noreply@gongetz.com'; 
          $mail->FromName = $SchoolName;

          //To address and name
          $mail->addAddress($Email,$ConsumerFName);

          //Address to which recipient will reply
          $mail->addReplyTo($Email,$ConsumerFName);

          //CC and BCC
          $mail->addCC("gngsoftech@gmail.com");
          
          //Send HTML or Plain Text email
          $mail->isHTML(true);

          $mail->Subject = "$SchoolName  - $title";
          $mail->Body ="
          <html>
            <head>
              <meta name='viewport' content='width=device-width'>
              <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
              <title>Simple Transactional Email</title>
              <style>
              /* -------------------------------------
                  INLINED WITH htmlemail.io/inline
              ------------------------------------- */
              /* -------------------------------------
                  RESPONSIVE AND MOBILE FRIENDLY STYLES
              ------------------------------------- */
              @media only screen and (max-width: 620px) {
                table[class=body] h1 {
                  font-size: 28px !important;
                  margin-bottom: 10px !important;
                }
                table[class=body] p,
                      table[class=body] ul,
                      table[class=body] ol,
                      table[class=body] td,
                      table[class=body] span,
                      table[class=body] a {
                  font-size: 16px !important;
                }
                table[class=body] .wrapper,
                      table[class=body] .article {
                  padding: 10px !important;
                }
                table[class=body] .content {
                  padding: 0 !important;
                }
                table[class=body] .container {
                  padding: 0 !important;
                  width: 100% !important;
                }
                table[class=body] .main {
                  border-left-width: 0 !important;
                  border-radius: 0 !important;
                  border-right-width: 0 !important;
                }
                table[class=body] .btn table {
                  width: 100% !important;
                }
                table[class=body] .btn a {
                  width: 100% !important;
                }
                table[class=body] .img-responsive {
                  height: auto !important;
                  max-width: 100% !important;
                  width: auto !important;
                }
              }

              /* -------------------------------------
                  PRESERVE THESE STYLES IN THE HEAD
              ------------------------------------- */
              @media all {
                .ExternalClass {
                  width: 100%;
                }
                .ExternalClass,
                      .ExternalClass p,
                      .ExternalClass span,
                      .ExternalClass font,
                      .ExternalClass td,
                      .ExternalClass div {
                  line-height: 100%;
                }
                .apple-link a {
                  color: inherit !important;
                  font-family: inherit !important;
                  font-size: inherit !important;
                  font-weight: inherit !important;
                  line-height: inherit !important;
                  text-decoration: none !important;
                }
                #MessageViewBody a {
                  color: inherit;
                  text-decoration: none;
                  font-size: inherit;
                  font-family: inherit;
                  font-weight: inherit;
                  line-height: inherit;
                }
                .btn-primary table td:hover {
                  background-color: #34495e !important;
                }
                .btn-primary a:hover {
                  background-color: #34495e !important;
                  border-color: #34495e !important;
                }
              }
              </style>
            </head>
            <body class='' style='background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;'>
              <span class='preheader' style='color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;'> You got this email because you're a member of.. </span>
              <table border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;'>
                <tr>
                  <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                  <td class='container' style='font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;'>
                    <div class='content' style='box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;'>

                      <!-- START CENTERED WHITE CONTAINER -->
                      <table class='main' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;'>

                        <!-- START MAIN CONTENT AREA -->
                        <tr>
                          <td class='wrapper' style='font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;'>
                            <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                              <tr>
                                <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>
                                  <p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;'> 
                                    <p?>Hi </p><a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'>$ConsumerFName $ConsumerLName</a>,
                                    <p>You've received this email because you're a member of <a href='https://smartschool.gongetz.com/school.php?id=$school_id'>$SchoolName</a></p>
                                    <p>Here's the latest News <a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'> $title </a> from $FromNameF $FromNameL on $date and we thought it might need your attention.</p>
                                    <p>Thanks,<br/>
                                    <p>Go N Getz</p>
                                    <p><small>Please don't reply to this email, it won't go anyway except to our great black hole.</small></p>
                                  </p>
                                  <table border='0' cellpadding='0' cellspacing='0' class='btn btn-primary' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;'>
                                    <tbody>
                                      <tr>
                                        <td align='left' style='font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;'>
                                          <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;'>
                                            <tbody>
                                              <tr>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </table>
                          </td>
                        </tr>

                      <!-- END MAIN CONTENT AREA -->
                      </table>

                      <!-- START FOOTER -->
                      <div class='footer' style='clear: both; Margin-top: 10px; text-align: center; width: 100%;'>
                        <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                          <tr>
                            <td class='content-block' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                              <span class='apple-link' style='color: #999999; font-size: 12px; text-align: center;'>G&G Softech Sdn Bhd, 75-1, jalan pudu lama, 50200, wilayah persekutuan, kuala lumpur</span>
                              <br> Don't like these emails? <a href='mailto:care@gongetz.com' class='btn btn-danger btn-sm'>Report Spam</a>.
                            </td>
                          </tr>
                          <tr>
                            <td class='content-block powered-by' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                            <a href='' style='color: #999999; font-size: 12px; text-align: center; text-decoration: none;'>gongetz.com</a>.
                            </td>
                          </tr>
                        </table>
                      </div>
                      <!-- END FOOTER -->

                    <!-- END CENTERED WHITE CONTAINER -->
                    </div>
                  </td>
                  <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
                </tr>
              </table>
            </body>
          </html>";
        $mail->AltBody = "This is the plain text version of the email content";
        try { $mail->send();} 
        catch (Exception $e) { echo "Mailer Error: " . $mail->ErrorInfo;}
        }
      }
    }
  }
}