<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require_once "vendor/autoload.php";
if (isset($_POST['AddStaffFormSubmit']))
{
    $varClasscategory = "";
    $varConsumerIDNo = $_POST['txtConsumerIDNo'];
    $varStaffdepartment = $_POST['txtStaffdepartment'];
    $varClasscategory = $_POST['txtClasscategory'];
    $varaccesslevel = $_POST['Stafflevel'];

    // start : email blaster
    $AddDate = new MongoDB\BSON\UTCDateTime((new DateTime('now'))->getTimestamp()*1000);
    $utcdatetime = new MongoDB\BSON\UTCDateTime(strval($AddDate));
    $datetime = $utcdatetime->toDateTime()->setTimezone(new \DateTimeZone(date_default_timezone_get()));
    $date = date_format($datetime,"d M Y");

    $varschoolID = strval($_SESSION["loggeduser_schoolID"]);
    $FromNameF = ($_SESSION["loggeduser_consumerFName"]);
    $FromNameL = ($_SESSION["loggeduser_consumerLName"]);
    $FromconsumerIDNo = strval($_SESSION["loggeduser_consumerIDNo"]);
    $FromconsumerIDType = ($_SESSION["loggeduser_consumerIDType"]);
    
    $SchoolName = ($_SESSION["loggeduser_schoolName"]);
    $SchoolEmail = ($_SESSION["loggeduser_SchoolsEmail"]);
    $SchoolPhone = ($_SESSION["loggeduser_schoolsPhoneNo"]);
    $SchoolAddress = ($_SESSION["loggeduser_schoolsAddress"]);

    $filter = ['ConsumerIDNo'=>$varConsumerIDNo];
    $query = new MongoDB\Driver\Query($filter);
    $cursor = $GoNGetzDatabase->executeQuery('GoNGetz.Consumer',$query);
  
    foreach ($cursor as $document)
    {
      $ConsumerFName = strval($document->ConsumerFName);
      $ConsumerLName = strval($document->ConsumerLName);
      $ConsumerIDType = strval($document->ConsumerIDType);
      $ConsumerIDNo = strval($document->ConsumerIDNo);
      $Email = strval($document->ConsumerEmail);
  
      if($Email != "")
      {
        $Email = strval($document->ConsumerEmail);
  
        //PHPMailer Object
        $mail = new PHPMailer(true);
        $mail->SMTPOptions = array(
            'ssl' => array(
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true
            )
        );
        //Argument true in constructor enables exceptions
        //$mail->SMTPDebug = 2;
        $mail->isSMTP();
        $mail->Host = 'mail.gongetz.com';
        $mail->SMTPAuth = true;
        $mail->Username = 'noreply@gongetz.com'; 
  
        //paste one generated by Mailtrap
        $mail->Password = 'zaq12wsx'; 
  
        //paste one generated by Mailtrap
        $mail->SMTPSecure = 'tls';
        $mail->AuthType = 'PLAIN';
        $mail->Port = 25;
  
        //From email address and name
        $mail->From =  'noreply@gongetz.com'; 
        $mail->FromName = $SchoolName;
  
        //To address and name
        $mail->addAddress($Email,$ConsumerFName);
  
        //Address to which recipient will reply
        $mail->addReplyTo($Email,$ConsumerFName);
  
        //CC and BCC
        $mail->addCC("gngsoftech@gmail.com");
        
        //Send HTML or Plain Text email
        $mail->isHTML(true);
  
        $mail->Subject = "$SchoolName";
        $mail->Body ="
        <html>
        <head>
          <meta name='viewport' content='width=device-width'>
          <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
          <title>Simple Transactional Email</title>
          <style>
          /* -------------------------------------
              INLINED WITH htmlemail.io/inline
          ------------------------------------- */
          /* -------------------------------------
              RESPONSIVE AND MOBILE FRIENDLY STYLES
          ------------------------------------- */
          @media only screen and (max-width: 620px) {
            table[class=body] h1 {
              font-size: 28px !important;
              margin-bottom: 10px !important;
            }
            table[class=body] p,
                  table[class=body] ul,
                  table[class=body] ol,
                  table[class=body] td,
                  table[class=body] span,
                  table[class=body] a {
              font-size: 16px !important;
            }
            table[class=body] .wrapper,
                  table[class=body] .article {
              padding: 10px !important;
            }
            table[class=body] .content {
              padding: 0 !important;
            }
            table[class=body] .container {
              padding: 0 !important;
              width: 100% !important;
            }
            table[class=body] .main {
              border-left-width: 0 !important;
              border-radius: 0 !important;
              border-right-width: 0 !important;
            }
            table[class=body] .btn table {
              width: 100% !important;
            }
            table[class=body] .btn a {
              width: 100% !important;
            }
            table[class=body] .img-responsive {
              height: auto !important;
              max-width: 100% !important;
              width: auto !important;
            }
          }
  
          /* -------------------------------------
              PRESERVE THESE STYLES IN THE HEAD
          ------------------------------------- */
          @media all {
            .ExternalClass {
              width: 100%;
            }
            .ExternalClass,
                  .ExternalClass p,
                  .ExternalClass span,
                  .ExternalClass font,
                  .ExternalClass td,
                  .ExternalClass div {
              line-height: 100%;
            }
            .apple-link a {
              color: inherit !important;
              font-family: inherit !important;
              font-size: inherit !important;
              font-weight: inherit !important;
              line-height: inherit !important;
              text-decoration: none !important;
            }
            #MessageViewBody a {
              color: inherit;
              text-decoration: none;
              font-size: inherit;
              font-family: inherit;
              font-weight: inherit;
              line-height: inherit;
            }
            .btn-primary table td:hover {
              background-color: #34495e !important;
            }
            .btn-primary a:hover {
              background-color: #34495e !important;
              border-color: #34495e !important;
            }
          }
          </style>
        </head>
        <body class='' style='background-color: #f6f6f6; font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; line-height: 1.4; margin: 0; padding: 0; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;'>
          <span class='preheader' style='color: transparent; display: none; height: 0; max-height: 0; max-width: 0; opacity: 0; overflow: hidden; mso-hide: all; visibility: hidden; width: 0;'> You got this email because you're a member of.. </span>
          <table border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background-color: #f6f6f6;'>
            <tr>
              <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
              <td class='container' style='font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; Margin: 0 auto; max-width: 580px; padding: 10px; width: 580px;'>
                <div class='content' style='box-sizing: border-box; display: block; Margin: 0 auto; max-width: 580px; padding: 10px;'>
  
                  <!-- START CENTERED WHITE CONTAINER -->
                  <table class='main' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #ffffff; border-radius: 3px;'>
  
                    <!-- START MAIN CONTENT AREA -->
                    <tr>
                      <td class='wrapper' style='font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 20px;'>
                        <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                          <tr>
                            <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>
                              <p style='font-family: sans-serif; font-size: 14px; font-weight: normal; margin: 0; Margin-bottom: 15px;'> 
                                <p>Hi </p><a href='https://smartschool.gongetz.com/profile.php?id=$ConsumerIDNo'>$ConsumerFName $ConsumerLName</a>,
                                <p>your personal data has been exposed  to <a href='https://smartschool.gongetz.com/profile.php?id=$FromconsumerIDNo'>$FromNameF $FromNameL</a> with $FromconsumerIDType $FromconsumerIDNo on $date. If you found out this is an error, kindly contact:
                                  <ul>
                                      <li><a href='https://smartschool.gongetz.com/school.php?id=$varschoolID'>$SchoolName</a></li>
                                      <li>Phone: $SchoolPhone</li>
                                      <li>Email: $SchoolEmail</li>
                                      <li>Address: $SchoolAddress</li>
                                  </ul>
                                </p>
                                <p>Thanks,<br/>
                                <p>Go N Getz</p>
                                <p><small>Please don't reply to this email, it won't go anyway except to our great black hole.</small></p>
                              </p>
                              <table border='0' cellpadding='0' cellspacing='0' class='btn btn-primary' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; box-sizing: border-box;'>
                                <tbody>
                                  <tr>
                                    <td align='left' style='font-family: sans-serif; font-size: 14px; vertical-align: top; padding-bottom: 15px;'>
                                      <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: auto;'>
                                        <tbody>
                                          <tr>
                                          </tr>
                                        </tbody>
                                      </table>
                                    </td>
                                  </tr>
                                </tbody>
                              </table>
                            </td>
                          </tr>
                        </table>
                      </td>
                    </tr>
                  <!-- END MAIN CONTENT AREA -->
                  </table>
  
                  <!-- START FOOTER -->
                  <div class='footer' style='clear: both; Margin-top: 10px; text-align: center; width: 100%;'>
                    <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                      <tr>
                        <td class='content-block' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                          <span class='apple-link' style='color: #999999; font-size: 12px; text-align: center;'>G&G Softech Sdn Bhd, 75-1, jalan pudu lama, 50200, wilayah persekutuan, kuala lumpur</span>
                          <br> Don't like these emails? <a href='mailto:care@gongetz.com' class='btn btn-danger btn-sm'>Report Spam</a>.
                        </td>
                      </tr>
                      <tr>
                        <td class='content-block powered-by' style='font-family: sans-serif; vertical-align: top; padding-bottom: 10px; padding-top: 10px; font-size: 12px; color: #999999; text-align: center;'>
                        <a href='' style='color: #999999; font-size: 12px; text-align: center; text-decoration: none;'>gongetz.com</a>.
                        </td>
                      </tr>
                    </table>
                  </div>
                  <!-- END FOOTER -->
  
                <!-- END CENTERED WHITE CONTAINER -->
                </div>
              </td>
              <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>&nbsp;</td>
            </tr>
          </table>
        </body>
      </html>
      ";
      $mail->AltBody = "This is the plain text version of the email content";
  
      try { $mail->send();} 
  
      catch (Exception $e) { echo "Mailer Error: " . $mail->ErrorInfo;}
      }
    }

    // end : email blaster
    $filter = ['School_id'=>$_SESSION["loggeduser_schoolID"], 'DepartmentName'=>$varStaffdepartment];
    $query = new MongoDB\Driver\Query($filter);
    $cursor =$GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.SchoolsDepartment',$query);
    foreach ($cursor as $document)
    {
      $_SESSION["departmentid"] = strval($document->_id);
      $_SESSION["DepartmentName"] = strval($document->DepartmentName);
    }
    $filter = ['ConsumerIDNo'=>$varConsumerIDNo];
    $query = new MongoDB\Driver\Query($filter);
    $cursor =$GoNGetzDatabase->executeQuery('GoNGetz.Consumer',$query);
    foreach ($cursor as $document)
    {
      $IDcon = strval($document->_id);
      $ConsumerGroup_id = strval($document->ConsumerGroup_id);
      if($ConsumerGroup_id == '601b4cfd97728c027c01f187')
      {
        $count = 0;
        $end = 1;
        $filter2 = ['SchoolID'=>$_SESSION["loggeduser_schoolID"]];
        $query2 = new MongoDB\Driver\Query($filter2);
        $cursor2 =$GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.Staff',$query2);

        foreach ($cursor2 as $document2)
        {
          $count++;
          $ID = strval($document->_id);
          $ConsumerFName = strval($document->ConsumerFName);
          $ConsumerLName = strval($document->ConsumerLName);
          $ConsumerIDNo = strval($document->ConsumerIDNo);
          ?>
        <br><br><br><br><h2 style="text-align: center;">PLEASE CONFIRM BEFORE PROCEED</h2>
        <form id="submitaddstaff" name="submitaddstaff" action="index.php?page=stafflist" method="post">
          <div class="modal-dialog modal-lg modal-dialog-centered">
          <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="AddStaffModalLabel">Add Staff</h5>
                </div>
                <div class="modal-body">
                  <div class="form-group row">
                    <label for="staticStaffNo" class="col-sm-2 col-form-label">Staff Name</label>
                    <div class="col-sm-10">
                      <input class="form-control" value="<?php echo $ConsumerFName." ".$ConsumerLName; ?>" disabled>
                      <input type="hidden" name="txtaccesslevel" value="<?php echo  $varaccesslevel; ?>" >
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="staticStaffNo" class="col-sm-2 col-form-label">MyKad</label>
                    <div class="col-sm-10">
                      <input class="form-control" value="<?php echo $ConsumerIDNo; ?>" disabled><br>
                      <input type="hidden" name="txtConsumerIDNo" value="<?php echo  $ConsumerIDNo; ?>" >
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="staticStaffNo" class="col-sm-2 col-form-label">Group</label>
                    <div class="col-sm-10">
                      <input class="form-control" value="SCHOOL" disabled>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="staticStaffNo" class="col-sm-2 col-form-label">Department</label>
                    <div class="col-sm-10">
                      <input class="form-control" value="<?php echo $varStaffdepartment; ?>" disabled><br>
                    </div>
                  </div>
                  <?php
                  if ($varaccesslevel == '0')
                  {
                    if ($varClasscategory == '')
                    {
                      ?>
                      <input type="hidden" name="txtteacherclass" value="" >
                      <?php
                    }
                    else
                    {
                      ?>
                      <div class="form-group row">
                        <label for="staticStaffNo" class="col-sm-2 col-form-label">Class Category</label>
                        <div class="col-sm-10">
                          <input class="form-control" value="<?php echo $varClasscategory; ?>" disabled><br>
                        </div>
                      </div>
                      <div id="teacherbox">
                        <div class="form-group row">
                        <label for="txtteacherclass" class="col-sm-2 col-form-label">Class</label>
                        <div class="col-sm-10">
                          <select class="form-control" id="txtteacherclass" name="txtteacherclass">
                            <?php
                            $filter1 = ['SchoolID'=>$_SESSION["loggeduser_schoolID"], 'ClassCategory'=>$varClasscategory];
                            $query1 = new MongoDB\Driver\Query($filter1);
                            $cursor1 =$GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.Classrooms',$query1);
                            foreach ($cursor1 as $document1):
                            ?>
                            <option value="<?=($document1->_id)?>"><?=($document1->ClassName)?></option>
                            <?php
                            endforeach
                            ?>
                          </select>
                        </div>
                      </div>
                      </div>
                      <?php
                    }
                  }
                else
                {
                ?>
                <input type="hidden" name="txtteacherclass" value="" >
                <?php
                }
                ?>
                  <div class="form-group row">
                    <label for="staticStaff" class="col-sm-2 col-form-label">Staff Status</label>
                    <div class="col-sm-10">
                      <select class="form-control" id="sltStatus" name="txtStaffstatus" >
                        <option value="ACTIVE">ACTIVE</option>
                        <option value="INACTIVE">INACTIVE</option>
                      </select>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button  onclick="index.php?page=stafflist" class="btn btn-secondary">Close</button>
                  <button type="submit" class="btn btn-success" name="submitaddstaff">Confirm</button>
                </div>
              </div>
          </div>
        </form>
        <?php
        if ($count == $end) break;
        }
        }
        else
        {
        ?>
        <br><br><br><br><div class="alert alert-danger" role="alert">
        <h2 style="text-align: center;">AUTHORIZED PERSONNEL ONLY</h2>
        <form id="submitstaff" name="submitstaff" action="index.php?page=stafflist" method="post">
          <div class="modal-dialog modal-lg modal-dialog-centered">
          <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="AddStaffModalLabel">Add Staff</h5>
                </div>
                <div class="modal-body">
                  <div class="form-group row">
                    <label for="staticStaffNo" class="col-sm-2 col-form-label">MyKad</label>
                    <div class="col-sm-10">
                      <input class="form-control" value="<?php echo $varConsumerIDNo; ?>" disabled>
                    </div>
                  </div>
                  <div class="form-group row">
                    <label for="staticStaffNo" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                      <input class="form-control" value="UNAUTHORIZED" disabled>
                    </div>
                  </div>
                <div class="modal-footer">
                  <button onclick="index.php?page=stafflist" class="btn btn-secondary" >Close</button>
                </div>
              </div>
          </div>
          </div>
          </form>
          </div>
          <?php
          }
          }
          }
          if (isset($_POST['EditStaffFormSubmit']))
          {
            $varClasscategory = $_POST['txtClasscategory'];
            $varteacherid = $_POST['teacherid'];
            $filter = ['SchoolID'=>$_SESSION["loggeduser_schoolID"], 'ConsumerID'=>$varteacherid];
            $query = new MongoDB\Driver\Query($filter);
            $cursor =$GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.Staff',$query);
            foreach ($cursor as $document)
            {
              $ConsumerID = strval($document->ConsumerID);
              $ConsumerID = new \MongoDB\BSON\ObjectId($ConsumerID);
              
              $filter = ['_id'=>$ConsumerID];
              $query = new MongoDB\Driver\Query($filter);
              $cursor =$GoNGetzDatabase->executeQuery('GoNGetz.Consumer',$query);
              foreach ($cursor as $document)
              {
                $ConsumerFName = strval($document->ConsumerFName);
              }
            }
            ?>
            <br><br><br><br><h2 style="text-align: center;">PLEASE CONFIRM BEFORE PROCEED</h2>
            <form id="submiteditstaff" name="submiteditstaff" action="index.php?page=stafflist" method="post">
            <div class="modal-dialog modal-lg modal-dialog-centered">
            <div class="modal-content">
                    <div class="modal-header">
                    <h5 class="modal-title" id="editclassModalLabel">Edit Class</h5>
                    </div>
                    <div class="modal-body">
                    <div class="form-group row">
                        <label for="staticStaffNo" class="col-sm-2 col-form-label">Staff Name</label>
                        <div class="col-sm-10">
                        <input class="form-control" value="<?php echo $ConsumerFName; ?>" disabled>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticStaffNo" class="col-sm-2 col-form-label">Class Category</label>
                        <div class="col-sm-10">
                        <input class="form-control" value="<?php echo $varClasscategory; ?>" disabled>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="staticStaffNo" class="col-sm-2 col-form-label">Class Teacher</label>
                        <div class="col-sm-10">
                        <select class="form-select" id="sltteacherclass" name="txtteacherclass">
                            <?php
                            $filter1 = ['SchoolID'=>$_SESSION["loggeduser_schoolID"], 'ClassCategory'=>$varClasscategory];
                            $query1 = new MongoDB\Driver\Query($filter1);
                            $cursor1 =$GoNGetzDatabase->executeQuery('GoNGetzSmartSchool.Classrooms',$query1);
                            foreach ($cursor1 as $document1):
                            ?>
                            <option value="<?=($document1->_id)?>"><?=($document1->ClassName)?></option>
                            <?php
                            endforeach 
                            ?>
                        </select>
                        </div>
                    </div>
                    </div>
                    <div class="modal-footer">
                    <input type="hidden" class="form-control" id="staticStaffNo" name="txtClasscategory" value="<?php echo  $varClasscategory; ?>">
                    <input type="hidden" class="form-control" id="staticStaffNo" name="teacherid" value="<?php echo  $varteacherid; ?>">
                    <button  onclick="index.php?page=stafflist" class="btn btn-secondary" >Close</button>
                    <button type="submit" class="btn btn-success" name="submiteditstaff">Confirm</button>
                    </div>
                </div>
            </div>
            </form>
            <?php
            }
            ?>